app = "luxsuv-backend"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
builder = "heroku/builder:24"
buildpacks = ["heroku/go"]

[env]
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1