package data

import "time"

// User represents a user entity (e.g., driver) in the system.
type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"` // Store hashed passwords in production
	Role      string    `json:"role"`     // e.g., "driver"
	CreatedAt time.Time `json:"created_at"`
}

// BookRide represents a ride booking entity.
type BookRide struct {
	ID                 int64  `json:"id"` // Generated by database
	YourName           string `json:"your_name"`
	Email              string `json:"email"`
	PhoneNumber        string `json:"phone_number"`
	RideType           string `json:"ride_type"`
	PickupLocation     string `json:"pickup_location"`
	DropoffLocation    string `json:"dropoff_location"`
	Date               string `json:"date"` // Consider using time.Time later for better type safety
	Time               string `json:"time"` // Consider using time.Time later for better type safety
	NumberOfPassengers int    `json:"number_of_passengers"`
	NumberOfLuggage    int    `json:"number_of_luggage"`
	AdditionalNotes    string `json:"additional_notes"`
}
